#!/bin/sh

lb clean noauto "${@}"

rm -f  config/binary config/bootstrap config/chroot config/common config/source
rm -rf config/includes.chroot/root config/includes.chroot/home
rm -f  config/package-lists/desktop.list.chroot
rm -f  config/bootloaders/isolinux/splash.svg
rm -f  config/bootloaders/syslinux/splash.svg
rm -f  build.log
