#!/bin/sh

lb clean noauto "${@}"

rm -f  config/binary config/bootstrap config/chroot config/common config/source
rm -rf config/chroot_local-includes/root config/package-lists
rm -f config/bootloaders/isolinux/splash.svg
rm -f config/bootloaders/syslinux/splash.svg
rm -f  build.log
