#!/bin/bash -e

# some fancy colors
RED=$(tput setaf 1)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)

# current architecture
arch=$(dpkg --print-architecture)

# options
lb_opts=""
dist="aequorea"
dist_version="1.1"
dist_reltag="BETA2"

if [ -z "$FLAVOR" ]; then
  FLAVOR="kde"
  echo "${RED}${BRIGHT}WARNING WARNING WARNING${NORMAL}"
  echo "${BRIGHT}FLAVOR is not defined, choosing $FLAVOR by default."
  echo "Set FLAVOR to 'gnome' if you want a gnome desktop${NORMAL}"
fi

# live-build doesn't work if --parent-debian-distribution is unknown of
# debian-cd => we have to put a symlink so that it deals with Tanglu like jessie/sid
if [ ! -e "/usr/share/live/build/data/debian-cd/$dist" ]; then
  if [ -w /usr/share/live/build/data/debian-cd ]; then
    ln -sf sid "/usr/share/live/build/data/debian-cd/$dist"
  else
    echo "ERROR: Run this first:"
    echo "ln -sf sid /usr/share/live/build/data/debian-cd/$dist"
    exit 1
  fi
fi

case "$arch" in
  amd64)
    lb_opts="$lb_opts --debian-installer live"
  ;;
  i386)
    lb_opts="$lb_opts --debian-installer live --linux-flavours 686-pae"
  ;;
  *)
    echo "WARNING: configuration not tested on arch $arch" >&2
  ;;
esac

# create some directories which we will need later
mkdir -p config/package-lists
mkdir -p config/chroot_local-includes

DEBIAN_INSTALLER_CONF="--debian-installer-distribution '$dist'"
# NOTE: We currently disable d-i and only use the custom live-installer
DEBIAN_INSTALLER_CONF=""

# configure selected flavor
case "$FLAVOR" in
  "kde"|"KDE")
    FLAVOR="KDE"
    FLAVOR_PRETTY="KDE Plasma Desktop"
    # create package config
    cat > config/package-lists/desktop.list.chroot <<EOF
tanglu-standard
grub2
tanglu-kde
tanglu-live-installer-slideshow-kde
tanglu-live-installer
EOF
    cp -r config/kde-chroot_local-includes/root config/chroot_local-includes/root
  ;;
  "gnome"|"GNOME")
    FLAVOR="GNOME"
    FLAVOR_PRETTY="GNOME Desktop"
    # create package config
    cat > config/package-lists/desktop.list.chroot <<EOF
tanglu-standard
grub2
tanglu-gnome
tanglu-live-installer-slideshow-gnome
tanglu-live-installer
EOF
  ;;
esac

# create a pretty version name, containing all information
if [ x"$dist_reltag" = x"" ]; then
  VERSION_PRETTY="$dist_version ($dist)"
else
  VERSION_PRETTY="$dist_version [$dist_reltag] ($dist)"
fi

# update our splash screen
sed -e s/@FLAVOR_PRETTY@/"$FLAVOR_PRETTY"/g config/bootloaders/splash.svg.in > config/bootloaders/splash.svg
sed -i s/@VERSION@/"$VERSION_PRETTY"/g config/bootloaders/splash.svg
cp -f config/bootloaders/splash.svg config/bootloaders/isolinux/
mv -f config/bootloaders/splash.svg config/bootloaders/syslinux/

lb config noauto \
    --distribution "$dist" \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free" \
    --mirror-bootstrap http://archive.tanglu.org/tanglu \
    --mirror-binary http://archive.tanglu.org/tanglu \
    --keyring-packages tanglu-archive-keyring \
    --build-with-chroot false \
    --bootloader syslinux \
    --security false \
    --updates false \
    --firmware-binary true \
    --firmware-chroot true \
    --initsystem systemd \
    --iso-application "Tanglu GNU/Linux" \
    --iso-publisher "Tanglu Project" \
    --iso-volume "Tanglu $dist_version $FLAVOR Live" \
    --image-name tanglu-${FLAVOR,,}-live \
    $DEBIAN_INSTALLER_CONF \
    $lb_opts \
    "${@}"
