#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##                    2014 Matthias Klumpp <mak@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

Cmdline ()
{
        # Reading kernel command line
        for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
        do
                case "${_PARAMETER}" in
                        live-config.username=*|username=*)
                                LIVE_USERNAME="${_PARAMETER#*username=}"
                                ;;
                esac
        done
}

Init ()
{
        # Checking if package is installed or already configured
        if [ ! -e /var/lib/dpkg/info/sddm.list ] || \
           [ -e /var/lib/live/config/sddm ]
        then
                exit 0
        fi

        echo -n " sddm"
}

Config ()
{
        if [ ! -e /etc/sddm.conf ]
        then
                exit 0
        fi

        # autologin
        sed -i -r -e "s|^User=.*\$|User=${LIVE_USERNAME}|" \
        /etc/sddm.conf

        # NOTE: We don't set relogin to true, because SDDM is currently crashing in that case.
        # To re-enable this, use -e "s|^Relogin=.*\$|Relogin=true|" \

        # Avoid xinit
        touch /var/lib/live/config/xinit

        # Creating state file
        touch /var/lib/live/config/sddm
}

Cmdline
Init
Config
